services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: gophermart
      POSTGRES_USER: gophermart
      POSTGRES_PASSWORD: gophermart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gophermart"]
      interval: 5s
      timeout: 5s
      retries: 5

  gophermart:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RUN_ADDRESS: ":8080"
      DATABASE_URI: "postgres://gophermart:gophermart@postgres:5432/gophermart?sslmode=disable"
      ACCRUAL_SYSTEM_ADDRESS: "http://accrual:8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations

  accrual:
    image: accrual:latest
    ports:
      - "8081:8080"
    environment:
      RUN_ADDRESS: ":8080"
      DATABASE_URI: "postgres://gophermart:gophermart@postgres:5432/accrual?sslmode=disable"

volumes:
  postgres_data: 